#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

log() { echo "[xiaoqimanager] $*"; }

ensure_cmd() {
  local cmd="$1"
  local apt_pkg="$2"

  if command -v "$cmd" >/dev/null 2>&1; then
    log "dependency '$cmd' already installed"
    return
  fi

  if command -v apt-get >/dev/null 2>&1; then
    log "installing missing dependency: $cmd ($apt_pkg)"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y
    apt-get install -y "$apt_pkg"
  else
    log "dependency '$cmd' is missing. Please install package '$apt_pkg' manually."
    exit 1
  fi
}

ensure_file() {
  local src="$1"
  local dst="$2"
  if [[ -f "$dst" ]]; then
    log "skip existing file: $dst"
    return
  fi
  if [[ -f "$src" ]]; then
    cp "$src" "$dst"
    log "created file from template: $dst"
    return
  fi

  cat >"$dst" <<'ENV_EOF'
# generated by scripts/install.sh
# please fill your real values before starting each backend
ENV=dev
PORT=8000
ENV_EOF
  log "template missing, generated default config: $dst"
}

mkdir -p "$ROOT_DIR/backend/core-a" "$ROOT_DIR/backend/core-b" "$ROOT_DIR/config" "$ROOT_DIR/web"

ensure_cmd python3 python3
ensure_cmd curl curl

ensure_file "$ROOT_DIR/backend/core-a/.env.example" "$ROOT_DIR/backend/core-a/.env"
ensure_file "$ROOT_DIR/backend/core-b/.env.example" "$ROOT_DIR/backend/core-b/.env"

if [[ ! -f "$ROOT_DIR/config/services.json" ]]; then
  log "error: missing config/services.json"
  exit 1
fi

log "installation complete."
log "next: cd $ROOT_DIR && python3 app.py"
